# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
move_group:
  ros__parameters:
    robot_description_planning:
      joint_limits:
        #Arm jojnts --------------------------------
        arm_joint_1:
          has_acceleration_limits: true
          max_acceleration: 0.5236 # 30 deg/s^2
          has_deceleration_limits: true
          max_deceleration: -0.5236 # 30 deg/s^2
          has_velocity_limits: true
          max_velocity: 1.0472 # 60 deg/s
        arm_joint_2:
          has_acceleration_limits: true
          max_acceleration: 0.5236 # 30 deg/s^2
          has_deceleration_limits: true
          max_deceleration: -0.5236 # 30 deg/s^2
          has_velocity_limits: true
          max_velocity: 1.0472 # 60 deg/s
        arm_joint_3:
          has_acceleration_limits: true

          max_acceleration: 0.5236 # 30 deg/s^2
          has_deceleration_limits: true
          max_deceleration: -0.5236 # 30 deg/s^2
          has_velocity_limits: true
          max_velocity: 1.0472 # 60 deg/s
        arm_joint_4:
          has_acceleration_limits: true
          max_acceleration: 0.5236 # 30 deg/s^2
          has_deceleration_limits: true
          max_deceleration: -0.5236 # 30 deg/s^2
          has_velocity_limits: true
          max_velocity: 1.0472 # 60 deg/s
        arm_joint_5:
          has_acceleration_limits: true
          max_acceleration: 0.5236 # 30 deg/s^2
          has_deceleration_limits: true
          max_deceleration: -0.5236 # 30 deg/s^2
          has_velocity_limits: true
          max_velocity: 1.0472 # 60 deg/s
        arm_joint_6:
          has_acceleration_limits: true
          max_acceleration: 0.5236 # 30 deg/s^2
          has_deceleration_limits: true
          max_deceleration: -0.5236 # 30 deg/s^2
          has_velocity_limits: true
          max_velocity: 1.0472 # 60 deg/s

        #Base virtual joints --------------------------------
        # Virtual base joint planning limits
        base_x:
          has_position_limits: false
          has_velocity_limits: true
          max_velocity: 1.5  # m/s linear x
          has_acceleration_limits: true
          max_acceleration: 2.0

        base_y:
          has_position_limits: false
          has_velocity_limits: true
          max_velocity: 1.5  # m/s linear y
          has_acceleration_limits: true
          max_acceleration: 2.0

        base_theta:
          has_position_limits: false
          has_velocity_limits: true
          max_velocity: 6.0   # rad/s angular
          has_acceleration_limits: true
          max_acceleration: 8.0
