# MoveIt uses this configuration for controller management
move_group:
  ros__parameters:
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      controller_names:
        - arm_controller

      arm_controller:
        type: FollowJointTrajectory
        joints:
          - arm_joint_1
          - arm_joint_2
          - arm_joint_3
          - arm_joint_4
          - arm_joint_5
          - arm_joint_6
        action_ns: follow_joint_trajectory
        default: true
