
planning_plugins:
  - ompl_interface/OMPLPlanner

request_adapters:
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds

response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution

planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0

  SBLkConfigDefault:
    type: geometric::SBL
    range: 0.0

  ESTkConfigDefault:
    type: geometric::EST
    range: 0.0
    goal_bias: 0.05

  KPIECEkConfigDefault:
    type: geometric::KPIECE
    range: 0.0
    goal_bias: 0.05
    border_fraction: 0.9

# -------------------- ARM --------------------
arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - SBLkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
  longest_valid_segment_fraction: 0.01

# -------------------- BASE --------------------
base:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - SBLkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
  longest_valid_segment_fraction: 0.01
  projection_evaluator: joints(base_x, base_y, base_theta)

# -------------------- BASE WITH ARM --------------------
base_with_arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - SBLkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
  longest_valid_segment_fraction: 0.01
  projection_evaluator: joints(base_x, base_y, base_theta)

# -------------------- MISC --------------------
start_state_max_bounds_error: 0.1
