move_group:
  ros__parameters:
    # planning_scene_monitor.yaml
    publish_planning_scene: true
    publish_geometry_updates: true
    publish_state_updates: true
    publish_transforms_updates: true
    publish_robot_description_semantic: true

    monitored_planning_scene:
      filters:
        exclude_joints:
          - "roller_.*"           # exclude all passive roller joints
        ignore_missing_joints: true   # disables missing joint warnings
