# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    fake_base_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    omni_cont:
      type: omniwheel_drive_controller/OmniwheelDriveController


arm_controller:
  ros__parameters:
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
      - arm_joint_6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

fake_base_controller:
  ros__parameters:
      joints:
        - base_x
        - base_y
        - base_theta
      command_interfaces:
        - position   # we won't use these, but MoveIt requires them
      state_interfaces:
        - position
      state_publish_rate: 0.0

omni_cont:
  ros__parameters:
    reference_timeout: 0.9

    front_left_wheel_command_joint_name: "chassis_C1_joint"
    front_right_wheel_command_joint_name: "chassis_C2_joint"
    rear_right_wheel_command_joint_name: "chassis_C3_joint"
    rear_left_wheel_command_joint_name: "chassis_C4_joint"

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 } #Keep this 0
      wheels_radius: 0.0762 
      sum_of_robot_center_projection_on_X_Y_axis: 0.3692 #This is the distance from the robot center to wheel center

    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    enable_odom_tf: true
    

