# Bridge Parameter File
# These topics communicate from rviz (ROS2) to gazebo
# ---------------------------------------------------
# Clock
- ros_topic_name: "clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# TF
- ros_topic_name: "tf"
  gz_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Joint States
#- ros_topic_name: "/joint_states"
#  gz_topic_name: "/world/lab_world/model/main/joint_state"
#  ros_type_name: "sensor_msgs/msg/JointState"
#  gz_type_name: "gz.msgs.Model"
#  direction: GZ_TO_ROS

# Odom
- ros_topic_name: "/omni_cont/odometry"
  gz_topic_name: "/world/lab_world/model/main/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

## Cameras
# Camera 1
- ros_topic_name: "camera_1/camera_info"
  gz_topic_name: "camera_1/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Camera 2
- ros_topic_name: "camera_2/camera_info"
  gz_topic_name: "camera_2/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Camera 3
- ros_topic_name: "camera_3/camera_info"
  gz_topic_name: "camera_3/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Camera 4
- ros_topic_name: "camera_4/camera_info"
  gz_topic_name: "camera_4/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Camera 5
- ros_topic_name: "camera_5/camera_info"
  gz_topic_name: "camera_5/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Camera 6
- ros_topic_name: "camera_6/camera_info"
  gz_topic_name: "camera_6/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS