controller_manager:
  ros__parameters:
    update_rate: 10
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    omni_cont:
      type: omniwheel_drive_controller/OmniwheelDriveController

omni_cont:
  ros__parameters:
    reference_timeout: 0.9

    front_left_wheel_command_joint_name: "chassis_C1_joint"
    front_right_wheel_command_joint_name: "chassis_C2_joint"
    rear_right_wheel_command_joint_name: "chassis_C3_joint"
    rear_left_wheel_command_joint_name: "chassis_C4_joint"

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 } #Keep this 0
      wheels_radius: 0.0254 
      sum_of_robot_center_projection_on_X_Y_axis: 1.0 #This is the distance from the robot center to wheel center

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
    

