publisher_forward_PID_controller:
  ros__parameters:
    wait_sec_between_publish: 10
    publish_topic: "PID_cont/reference"

    goal_names: ["velocity1",velocity2,velocity3,velocity4]
    velocity1: [50.0, 0.0, -50.0, 0.0]
    velocity2: [0.0, -50.0, 0.0, 50.0]
    velocity3: [-50.0, 0.0, 50.0, 0.0]
    velocity4: [0.0, 50.0, 0.0, -50.0]