controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    velo_cont:
      type: velocity_controllers/JointGroupVelocityController

#Wheel Controller
velo_cont:
  ros__parameters:
    joints:
      - chassis_C1_joint
      - chassis_C2_joint
      - chassis_C3_joint
      - chassis_C4_joint

    gains:
      chassis_C1_joint: {p: 0.5, i: 0.3, d: 0.4, i_clamp_max: 5.0, i_clamp_min: -5.0, feedforward_gain: 1.0}
      chassis_C2_joint: {p: 0.5, i: 0.3, d: 0.4, i_clamp_max: 5.0, i_clamp_min: -5.0, feedforward_gain: 1.0}
      chassis_C3_joint: {p: 0.5, i: 0.3, d: 0.4, i_clamp_max: 5.0, i_clamp_min: -5.0, feedforward_gain: 1.0}
      chassis_C4_joint: {p: 0.5, i: 0.3, d: 0.4, i_clamp_max: 5.0, i_clamp_min: -5.0, feedforward_gain: 1.0}







