# Bridge Parameter File
# These topics communicate from rviz (ROS2) to gazebo
# ---------------------------------------------------
# Clock
- ros_topic_name: "clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Odom
- ros_topic_name: "/omni_cont/odometry"
  gz_topic_name: "/world/lab_world/model/main/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
