# This pipeline is for MoveIt Task Constructor (MTC)
planning_pipelines: ["mtc"]
mtc:
  # The planner to be used within MTC.
  # This can be set to any motion planner available in MoveIt,
  # such as OMPL or CHOMP. Here we use OMPL as specified in ompl_planning.yaml.
  planner_id: "ompl"

  # Path to OMPL planning configuration
  ompl_planning: "ompl_planning.yaml"

  # A list of request adapters. These are used to modify the planning request
  # before it is sent to the planner.
  request_adapters:
    - default_planner_request_adapter/FixStartStateBounds
    - default_planner_request_adapter/FixWorkspaceBounds
    - default_planner_request_adapter/FixStartStateCollision
    - default_planner_request_adapter/FixPathWithPostProcessor
